<?php

$str = '-';

/*$stringLength = new \Zend\Validator\StringLength(['min' => 2, 'max' => 10]);
$stringLength->setMessages([
    \Zend\Validator\StringLength::TOO_SHORT => 'Too short',
    \Zend\Validator\StringLength::TOO_LONG  => 'Too long',
]);

$alpha = new \Zend\I18n\Validator\Alpha();
$alpha->setMessages([
    \Zend\I18n\Validator\Alpha::NOT_ALPHA => 'Not alpha',
]);

//$alpha->setMessage('Not alpha', \Zend\I18n\Validator\Alpha::NOT_ALPHA);


$validatorChain = new \Zend\Validator\ValidatorChain();
$validatorChain->attach($stringLength);
$validatorChain->attach($alpha);
*/

/*$validatorChain = new \Zend\Validator\ValidatorChain();
$validatorChain->attachByName('StringLength', ['min' => 2, 'max' => 10]);
$validatorChain->attachByName('Alpha');


if ($validatorChain->isValid($str)) {
    echo 'Good';
} else {
    foreach ($validatorChain->getMessages() as $message) {
        echo "<div>{$message}</div>";
    }
}*/

/*$value = 10.0;

$floatValidator = new \Tutorial\Validator\FloatValidator();

if ($floatValidator->isValid($value)) {
    echo 'Yes';
} else {
    foreach ($floatValidator->getMessages() as $message) {
        echo "<div>{$message}</div>";
    }
}*/

/*use Zend\I18n\Translator\Translator;
$translator = new Translator();*/

/*$type = 'phparray';
$file = 'ru_RU.php';

$path = getcwd() . '/data/translator/' . $file;

if (is_file($path)) {
    $translator->addTranslationFile($type, $path);
    echo $translator->translate('home');
}*/


//echo $this->translator->translate('home');
//echo $this->translate('home');




?>
<?php
$headTitle = 'Example';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<p><?= $this->escapeHtml($this->url) ?></p>
<p><?= $this->widget ?></p>
<?= $this->getTime() ?>




<?php //echo $this->translate('home') ?>

<?php //echo $this->translate('home', null, 'ru') ?>







<?php $currentLang = $this->layout()->lang; ?>



<form method="get" id="changeLanguageForm" class="form-inline">
    <p class="text-right">
        <label for="languageElement"><?php echo $this->translate('Change current language') ?></label>
        <select id="languageElement" class="form-control" name="lang"
                onchange="$('#changeLanguageForm').submit()">
            <option <?php echo $currentLang === 'en_US' ? 'selected' : '' ?> value="en_US">English</option>
            <option <?php echo $currentLang === 'id_ID' ? 'selected' : '' ?> value="id_ID">Bahasa</option>
            <option <?php echo $currentLang === 'es_ES' ? 'selected' : '' ?> value="es_ES">Spanish</option>
            <option <?php echo $currentLang === 'ru_RU' ? 'selected' : '' ?> value="ru_RU">Russian</option>
        </select>
    </p>
</form>
<fieldset>
    <legend>Messages in current language (<?php echo $currentLang ?>)</legend>
    <ul>
        <li><?php echo $this->translate('Hello') ?></li>
        <li><?php echo $this->translate('Learn Zend Framework with this tutorials') ?></li>
        <li><?php echo $this->translate('This string is fetched from a gettext file') ?></li>
        <li><?php echo $this->translate('Zend Framework 2 is a web framework written in PHP') ?></li>
    </ul>
</fieldset>
<br>



