<ul class="breadcrumb">
    <?php
    // iterate through the pages
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php
            // if this isn't the last page, add a link and the separator:
            if ($key < count($this->pages) - 1):
                ?>
                <a href="<?= $page->getHref() ?>"><?= $this->translate($page->getLabel()) ?></a>
                <?php
            // otherwise, output the name only:
            else:
                ?>
                <?= $this->translate($page->getLabel()) ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
