<?php $this->headScript()->appendScript('$(function(){ $("ul.nav.navbar-nav li").eq(2).addClass("active") });'); ?>
<div class="row">
    <div class="col-sm-6">
        <h3><?= $this->translate($headTitle) ?></h3>
    </div>
    <div class="col-sm-6">
        <div class="pull-right admin-breadcrumb">
            <?= $this->navigation('admin_breadcrumbs')
                     ->setTranslator($this->plugin('translate')->getTranslator())
                     ->breadcrumbs()
                     ->setMinDepth(1)
                     ->setPartial('partial/breadcrumb') ?>
        </div>
    </div>
</div>
<hr>
