<?php
$this->headScript()->appendScript('$(function(){ $("ul.nav.navbar-nav li").eq(1).addClass("active") });');

$headTitle = 'Blog';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<br>
<div class="row">
    <div class="col-sm-3" id="left-aside">
        <?= $this->getCategories() ?>
    </div>
    <div class="col-sm-9">
        <?php if (! $this->article) : ?>
        <h3>List is empty</h3>
        <?php else : ?>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?= $this->escapeHtml($article->getTitle()) ?></h3>
                        </div>
                        <div class="panel-body">
                            <img src="<?= $this->basePath() ?>/img/home/no-image.jpg"
                                 width="400"
                                 heigth="300"
                                 class="img-responsive center-block"
                                 alt="<?= $this->escapeHtml($article->getTitle()) . '- image' ?>"
                            >
                            <hr>
                            <div><?= $this->escapeHtml($article->getContent()) ?></div>
                        </div>
                        <div class="panel-footer">
                            <div><a href="<?= $this->url('blog') ?>">&Lt; Back</a></div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<br>
