<?php
$this->headScript()->appendScript('$(function(){ $("ul.nav.navbar-nav li").eq(1).addClass("active") });');

$headTitle = $this->escapeHtml($this->categoryName);
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<br>
<div class="row">
    <div class="col-sm-3" id="left-aside">
        <?= $this->getCategories() ?>
    </div>
    <div class="col-sm-9">
        <?php if (count($this->articles) === 0) : ?>
        <h5>Category is empty</h5>
        <?php else : ?>
            <?php foreach ($this->articles as $article) : ?>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?= $this->escapeHtml($article->getTitle()) ?></h3>
                        </div>
                        <div class="panel-body">
                            <img src="<?= $this->basePath() ?>/img/home/no-image.jpg"
                                 width="100"
                                 heigth="80"
                                 class="img-responsive blog-image"
                                 alt="<?= $this->escapeHtml($article->getTitle()) . '- image' ?>"
                            >
                            <div><?= $this->escapeHtml($article->getShortContent()) ?></div>
                        </div>
                        <div class="panel-footer">
                            <div>
                                <a href="<?= $this->url('particle', ['id' => (int)$article->getId()]) ?>">
                                    Read more &Gt;
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <br>
            <?php
            echo $this->paginationControl(
                $this->articles,
                'sliding',
                'partial/paginatorForCategoryPage',
                ['route' => 'category']
            );
            ?>
        <?php endif; ?>
    </div>
</div>
<br>
