<?php
$headTitle = 'Admins';
$this->headTitle($headTitle);
?>
<?= $this->partial('partial/title-and-breadcrumb', ['headTitle' => $headTitle]) ?>
<div class="row">
    <div class="col-sm-12">
        <div class="pull-right app-message">
            <?php
            echo $this->flashMessenger()->render('success', ['success-message']);
            echo $this->flashMessenger()->render('error',   ['error-message']);
            ?>
        </div>
    </div>
</div>
<button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseTable" aria-expanded="false" aria-controls="collapseExample">
    <?= $this->translate('Admin\'s list') ?>
</button>
<br>
<br>
<div class="row collapse" id="collapseTable">
    <div class="col-sm-12">
        <?php if (! $this->users) : ?>
            <h4><?= $this->translate('Admin\'s list is empty') ?></h4>
        <?php else : ?>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Registration date</th>
                        <th>Actions</th>
                    </tr>
                    <?php foreach ($this->users as $user) : ?>
                        <?php
                        $role = $this->decryptLogin(false, $user->getRole());
                        $role = substr($role, strpos($role, '_') + 1);
                        ?>
                        <?php if ($role === 'admin') : ?>
                            <tr>
                                <td><?= ++$this->cntAdmin ?></td>
                                <td><?= $this->decryptLogin($user->getName()) ?></td>
                                <td><?= $user->getEmail() ?></td>
                                <td><?= $role ?></td>
                                <td><?= $user->getRegistrationDate()->format('d F Y') ?></td>
                                <td>
                                    <a href="#">Edit</a>
                                    &nbsp;&nbsp;|&nbsp;&nbsp;
                                    <a href="#">Delete</a>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endif; ?>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12">
        <?php if (! $this->users) : ?>
        <h4><?= $this->translate('User\'s list is empty') ?></h4>
        <?php else : ?>
        <h4><?= $this->translate('User\'s list') ?></h4>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Registration date</th>
                        <th>Actions</th>
                    </tr>
                    <?php foreach ($this->users as $user) : ?>
                    <?php
                        $role = $this->decryptLogin(false, $user->getRole());
                        $role = substr($role, strpos($role, '_') + 1);
                    ?>
                    <?php if ($role === 'user') : ?>
                    <tr>
                        <td><?= ++$this->cntUser ?></td>
                        <td><?= $this->decryptLogin($user->getName()) ?></td>
                        <td><?= $user->getEmail() ?></td>
                        <td><?= $role ?></td>
                        <td><?= $user->getRegistrationDate()->format('d F Y') ?></td>
                        <td>
                            <a href="#">Edit</a>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <a href="#">Delete</a>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endif; ?>
    </div>
</div>
