<?php
$headTitle = 'Manage admins';
$this->headTitle($headTitle);
?>
<?= $this->partial('partial/title-and-breadcrumb', ['headTitle' => $headTitle]) ?>
<div class="row">
    <div class="col-sm-12">
        <div class="pull-right app-message">
            <?php
            echo $this->flashMessenger()->render('success', ['success-message']);
            echo $this->flashMessenger()->render('error',   ['error-message']);
            ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <!-- Block form checking is empty admin's list  -->
        <?php $marker = false; ?>
        <?php foreach ($this->users as $user) : ?>
            <?php
            $role = $this->decryptLogin(false, $user->getRole());
            $role = substr($role, strpos($role, '_') + 1);

            if ($role === 'admin') {
                $marker = true;
                break;
            }
            ?>
        <?php endforeach; ?>
        <!-- End block -->

        <?php if (! $marker) : ?>
        <h4><?= $this->translate('Admin\'s list is empty') ?></h4>
        <?php else : ?>

        <h4><?= $this->translate('Admin\'s list') ?></h4>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <tr>
                        <th>#</th>
                        <th><?= $this->translate('Name') ?></th>
                        <th><?= $this->translate('Email') ?></th>
                        <th><?= $this->translate('Role') ?></th>
                        <th><?= $this->translate('Registration date') ?></th>
                        <th><?= $this->translate('Actions') ?></th>
                    </tr>
                    <?php foreach ($this->users as $user) : ?>
                        <?php
                        $role = $this->decryptLogin(false, $user->getRole());
                        $role = substr($role, strpos($role, '_') + 1);
                        ?>
                        <?php if ($role === 'admin') : ?>
                            <tr>
                                <td><?= ++$this->cnt ?></td>
                                <td><?= $this->decryptLogin($user->getName()) ?></td>
                                <td><?= $user->getEmail() ?></td>
                                <td><?= $role ?></td>
                                <td><?= $user->getRegistrationDate()->format('d F Y') ?></td>
                                <td>
                                    <a href="<?= $this->url('admin/admin', ['action' => 'edit', 'id' => (int)$user->getId()]) ?>">
                                        <?= $this->translate('Edit') ?>
                                    </a>
                                    &nbsp;&nbsp;|&nbsp;&nbsp;
                                    <a href="<?= $this->url('admin/admin', ['action' => 'delete', 'id' => (int)$user->getId()]) ?>">
                                        <?= $this->translate('Delete') ?>
                                    </a>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endif; ?>
    </div>
</div>
