<?= $this->doctype() ?>
<?php $user = $this->identity() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle() ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/jquery-filestyle.css'))
            ->prependStylesheet($this->basePath('css/j-confirm-action.css'))
            ->prependStylesheet($this->basePath('css/menu-accordion.css'))
            ->prependStylesheet($this->basePath('css/liMenuVert.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-sandstone.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/jquery-filestyle.min.js'))
            ->prependFile($this->basePath('js/j-confirm-action.js'))
            ->prependFile($this->basePath('js/menu-accordion.js'))
            ->prependFile($this->basePath('js/jquery.liMenuVert.js'))
            ->prependFile($this->basePath('js/app-script.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('top_navigation')
                             ->setTranslator($this->plugin('translate')->getTranslator())
                             ->menu()
                             ->setUlClass('nav navbar-nav')
                             ->render() ?>
                    <?php if (isset($user) && $user->getRole() !== null) : ?>
                        <?php $userRole = $this->decryptLogin(false, $this->escapeHtml($user->getRole())); ?>
                        <?php $userRole = substr($userRole, strpos($userRole, '_') + 1); ?>
                        <?php if($userRole === 'super' || $userRole === 'admin') : ?>
                        <ul class="nav navbar-nav">
                            <li><a href="/admin"><?= $this->translate('Admin') ?></a></li>
                        </ul>
                        <?php endif; ?>
                    <?php endif; ?>
                    <div class="registration-block pull-right">
                        <?php if ($user) : ?>
                            <span><?= $this->translate('Hi') ?>
                                <?= $this->decryptLogin($this->escapeHtml($user->getName())) ?>
                            </span>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <a href="/logout"><?= $this->translate('Logout') ?></a>
                        <?php else : ?>
                            <a href="/register"><?= $this->translate('Sign Up') ?></a>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <a href="/login"><?= $this->translate('Login') ?></a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
        </div>
        <footer class="footer">
            <hr>
            <div class="container">
            <p>&copy; <?= $this->getYear() ?> <?= $this->translate('by') ?> PHP-User. <?= $this->translate('All rights reserved') ?>.</p>
            </div>
        </footer>

        <a id="back-to-top"
           href="#"
           class="btn btn-primary btn-sm back-to-top"
           role="button"
           data-toggle="tooltip"
           data-placement="left"
        >
            <span class="glyphicon glyphicon-chevron-up"></span>
        </a>

        <?= $this->inlineScript() ?>
    </body>
</html>
