<?php
$headTitle = 'Add category';
$this->headTitle($headTitle);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/category', ['action' => 'add']));
$form->prepare();
?>
<?= $this->partial('partial/title-and-breadcrumb', ['headTitle' => $headTitle]) ?>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('csrf'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('parent'));
echo $this->formRow($form->get('isPublic'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
?>
