<?php
$headTitle = 'Edit category';
$this->headTitle($headTitle);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/category', ['action' => 'edit', 'id' => $this->id]));
$form->prepare();
?>
<?= $this->partial('partial/title-and-breadcrumb', ['headTitle' => $headTitle]) ?>
<div class="row">
    <div class="col-sm-6">
        <?= $this->form()->openTag($form) ?>
        <?= $this->formRow($form->get('csrf')) ?>
        <div class="form-group">
            <div class="col-sm-3">
                <?= $this->formLabel($form->get('name')) ?>
            </div>
            <div class="col-sm-9">
                <?= $this->formText($form->get('name')) ?>
                <?= $this->formElementErrors($form->get('name'), ['class' => 'form-element-errors']); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3">
                <?= $this->formLabel($form->get('parent')) ?>
            </div>
            <div class="col-sm-9">
                <?= $this->formSelect($form->get('parent')) ?>
                <?= $this->formElementErrors($form->get('parent')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3">
                <?= $this->formLabel($form->get('isPublic')) ?>
            </div>
            <div class="col-sm-9">
                <?= $this->formCheckbox($form->get('isPublic')) ?>
                <?= $this->translate($this->formElementErrors($form->get('isPublic'))) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-sm-offset-3">
                <?= $this->formSubmit($form->get('submit')) ?>
            </div>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>


