<?php
$headTitle = 'Categories';
$this->headTitle($headTitle);
?>
<?= $this->partial('partial/title-and-breadcrumb', ['headTitle' => $headTitle]) ?>
<div class="row">
    <div class="col-sm-6">
        <div><a href="<?= $this->url('admin/category', ['action' => 'add']) ?>" class="btn btn-default">Add category</a></div>
    </div>
    <div class="col-sm-6">
        <div class="pull-right app-message">
            <?php
            echo $this->flashMessenger()->render('success', ['success-message']);
            echo $this->flashMessenger()->render('error',   ['error-message']);
            ?>
        </div>
    </div>
</div>
