<?php
$headTitle = 'Blog';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->translate($headTitle) ?></h3>
    </div>
</div>
<br>
<div class="row">
    <div class="col-sm-3" id="left-aside">
        <?= $this->getCategories() ?>
    </div>
    <div class="col-sm-9">
        <?php if (! $this->articles) : ?>
        <h3>List is empty</h3>
        <?php else : ?>
            <?php foreach ($this->articles as $article) : ?>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?= $this->escapeHtml($article->getTitle()) ?></h3>
                        </div>
                        <div class="panel-body">
                            <img src="<?= $this->setImage($this->escapeHtml($article->getImage())) ?>"
                                 width="100"
                                 heigth="80"
                                 class="img-responsive blog-image"
                                 alt="<?= $this->escapeHtml($article->getTitle()) . '- image' ?>"
                            >
                            <div><?= nl2br($this->escapeHtml($article->getShortContent()), false) ?></div>
                        </div>
                        <div class="panel-footer">
                            <div>
                                <a href="<?= $this->url('particle', ['id' => (int)$article->getId()]) ?>">
                                    Read more &Gt;
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <br>
            <?php
            echo $this->paginationControl(
                $this->articles,
                'sliding',
                'partial/paginator',
                ['route' => 'blog']
            );

            ?>
        <?php endif; ?>
    </div>
</div>
<br>
