<?php
$headTitle = 'Admin';
$this->headTitle($headTitle);
?>
<?= $this->partial('partial/title-and-breadcrumb', ['headTitle' => $headTitle]) ?>
<div>
    <p><?= $this->translate('You have following capabilities') ?>:</p>
    <ul class="list-unstyled">
        <li><a href="<?= $this->url('admin/category') ?>"><?= $this->translate('Manage categories') ?></a></li>
        <li><a href="<?= $this->url('admin/article') ?>"><?= $this->translate('Manage articles') ?></a></li>
        <li><a href="<?= $this->url('admin/user') ?>"><?= $this->translate('Manage users') ?></a></li>
    </ul>
</div>
